spring:
  application:
    name: testSpring
  devtools:
    restart:
      enabled: true
  additional-paths: 'src/main/java,src/main/resources'
  poll-interval: 3000
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: taco_cloud